### ISSUE TITLE
Potentially non-portable regex

### ISSUE THREAD

**Issue by sundhaug92** [api0cradle/RedTeamScripts#1]
The following regex seems to only "fit" in your lab-environment, may want to add a way to override it
https://github.com/api0cradle/RedTeamScripts/blob/97e8d32eb490634370cb9baeb99dfdd6d1bc8514/offline_address_book_extractor.py#L25

Similarly https://github.com/api0cradle/RedTeamScripts/blob/97e8d32eb490634370cb9baeb99dfdd6d1bc8514/offline_address_book_extractor.py#L50
may not work in all countries

**Comment by api0cradle** [comment]
That first pattern is a static structure within exchange that see in all the udetails.oab files I have pulled.
Yeah, the phone pattern could potentially be different to catch more international numbers. We all know how fun it is to define regex :-)
